### ISSUE TITLE
Samsung smart TV detected as Linux computer

### ISSUE THREAD

**Issue by robertochiaveri** [barisaydinoglu/Detectizr#33]
Here's the userAgent of my smart TV:

Mozilla/5.0 (SMART-TV; X11; Linux i686) AppleWebKit/534.7 (KHTML, like Gecko) Version/5.0 Safari/534.7

It's currenlty identified as a Linux Computer
Hope it helps

R

**Comment by barisaydinoglu** [comment]
fixed with commit d52f4ac0ba374dd3f8eade37298e8efda3251b41
