### ISSUE TITLE
Windows Edge Support?

### ISSUE THREAD

**Issue by guillaumeroy1** [barisaydinoglu/Detectizr#38]
I would like to know if you planning to support Windows Edge anytime soon.

Here's the User Agent : 

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by jcbvm** [comment]
+1

**Comment by barisaydinoglu** [comment]
windows10 and edge support added 3904255bbf630331b3c969a0128b51d1c8705d94
