### ISSUE TITLE
Modernizr 3 compatibility?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [barisaydinoglu/Detectizr#39]
Is it planned or is it already there?

Thanks in advance.

**Comment by gspiker** [comment]
@julianxhokaxhiu After months of waiting for an update to make Detectizr compatible with Modernizr 3, I've discovered that it actually is already fully compatible. You just need to build Modernizr with the `Modernizr.addTest()` option checked in the Options column on the left panel.

**Comment by bichotll** [comment]
I created a simple pull request to update the README:
https://github.com/barisaydinoglu/Detectizr/pull/50

**Comment by julianxhokaxhiu** [comment]
Thank you! I'll close this issue then :) well done

**Comment by bichotll** [comment]
I'll ping @barisaydinoglu and see what's the story heh
